main: fr.pederobien.minecraftarea.AreaPlugin
name: minecraft-area
version: 1.0-SNAPSHOT
api-version: 1.13

description:
commands:
  area:
    description: This command is used to load or save minecraft blocks.
    permission: AreaPlugin.permission